<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8qwp8ni\srcDevItop_portalProductionDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8qwp8ni/srcDevItop_portalProductionDebugProjectContainer.php') {
    touch(__DIR__.'/Container8qwp8ni.legacy');

    return;
}

if (!\class_exists(srcDevItop_portalProductionDebugProjectContainer::class, false)) {
    \class_alias(\Container8qwp8ni\srcDevItop_portalProductionDebugProjectContainer::class, srcDevItop_portalProductionDebugProjectContainer::class, false);
}

return new \Container8qwp8ni\srcDevItop_portalProductionDebugProjectContainer(array(
    'container.build_hash' => '8qwp8ni',
    'container.build_id' => '53441847',
    'container.build_time' => 1548869209,
), __DIR__.\DIRECTORY_SEPARATOR.'Container8qwp8ni');
