<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'scope_validator' shared autowired service.

include_once $this->targetDirs[3].'/src/Helper/ScopeValidatorHelper.php';

return $this->services['scope_validator'] = new \Combodo\iTop\Portal\Helper\ScopeValidatorHelper(${($_ = isset($this->services['ModuleDesign']) ? $this->services['ModuleDesign'] : ($this->services['ModuleDesign'] = new \ModuleDesign('itop-portal'))) && false ?: '_'}, 'itop-portal', $this->getEnv('ITOP_CACHE_PATH'));
