<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('Combodo\\iTop\\Portal\\Controller\\BrowseBrickController:TreeToFlatLevelsProperties' => function () {
    return ${($_ = isset($this->services['service_locator.4qejj2v']) ? $this->services['service_locator.4qejj2v'] : $this->load('getServiceLocator_4qejj2vService.php')) && false ?: '_'};
}, 'Combodo\\iTop\\Portal\\Controller\\DefaultController:homeAction' => function () {
    return ${($_ = isset($this->services['service_locator.nartgnl']) ? $this->services['service_locator.nartgnl'] : $this->load('getServiceLocator_NartgnlService.php')) && false ?: '_'};
}, 'Combodo\\iTop\\Portal\\Controller\\BrowseBrickController::TreeToFlatLevelsProperties' => function () {
    return ${($_ = isset($this->services['service_locator.4qejj2v']) ? $this->services['service_locator.4qejj2v'] : $this->load('getServiceLocator_4qejj2vService.php')) && false ?: '_'};
}, 'Combodo\\iTop\\Portal\\Controller\\DefaultController::homeAction' => function () {
    return ${($_ = isset($this->services['service_locator.nartgnl']) ? $this->services['service_locator.nartgnl'] : $this->load('getServiceLocator_NartgnlService.php')) && false ?: '_'};
})));
