<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'bricks_collection' shared autowired service.

include_once $this->targetDirs[3].'/src/Bricks/BricksCollection.php';

return $this->services['bricks_collection'] = new \Combodo\iTop\Portal\Bricks\BricksCollection(${($_ = isset($this->services['ModuleDesign']) ? $this->services['ModuleDesign'] : ($this->services['ModuleDesign'] = new \ModuleDesign('itop-portal'))) && false ?: '_'});
