<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Combodo\iTop\Portal\Controller\ManageBrickController' shared autowired service.

include_once $this->targetDirs[3].'/src/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/src/Controller/BrickController.php';
include_once $this->targetDirs[3].'/src/Controller/ManageBrickController.php';

return $this->services['Combodo\iTop\Portal\Controller\ManageBrickController'] = new \Combodo\iTop\Portal\Controller\ManageBrickController();
