<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.4qejj2v' shared service.

return $this->services['service_locator.4qejj2v'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('bricksCollection' => function () {
    return ${($_ = isset($this->services['bricks_collection']) ? $this->services['bricks_collection'] : $this->load('getBricksCollectionService.php')) && false ?: '_'};
}, 'scopeValidator' => function () {
    return ${($_ = isset($this->services['scope_validator']) ? $this->services['scope_validator'] : $this->load('getScopeValidatorService.php')) && false ?: '_'};
}));
