<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.nartgnl' shared service.

return $this->services['service_locator.nartgnl'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('bricksCollection' => function () {
    return ${($_ = isset($this->services['bricks_collection']) ? $this->services['bricks_collection'] : $this->load('getBricksCollectionService.php')) && false ?: '_'};
}));
